"""ORM models package.

Importing this module registers every model against ``db.base.Base.metadata`` so Alembic
(`db/migrations/env.py`) and tests see the full schema. ``STAGE2_TABLES`` freezes the set
of tables created by migration 0002.
"""

from __future__ import annotations

from db.models.core import (
    ACTIVE_ALERT_STATES,
    ALERT_STATES,
    EMBEDDING_DIM,
    EMBEDDING_MODEL,
    EMBEDDING_MODEL_VERSION,
    REPORT_CONTENT_POLICY_DESCRIPTIVE_ONLY,
    REPORT_CONTENT_POLICY_PREDICTION_BACKED,
    Alert,
    AlertConditionState,
    AlertRule,
    Article,
    ArticleEmbedding,
    Claim,
    ClaimEvidence,
    Company,
    CompanyAlias,
    CompanyIdentifier,
    CompanyRiskRollup,
    CountryContextSnapshot,
    CountryIndicatorObservation,
    CountryIndicatorSeries,
    DailyIntelligenceSummary,
    EnergyDisruptionEvent,
    EnergyMarketSnapshot,
    EntityAlias,
    EntityIdentifier,
    EntityProfile,
    EntityRedirect,
    EntityRelationship,
    EntityResolutionRun,
    Event,
    EventAnalogy,
    EventArticle,
    EventCompany,
    EventEmbedding,
    EventEntity,
    EventIndustry,
    EventLocation,
    EventTimelineItem,
    EvidenceItem,
    ForecastScenario,
    GeocodingCache,
    GeoIncident,
    GeoIncidentImpact,
    HistoricalEpisode,
    HistoricalEpisodeEmbedding,
    HumanitarianReport,
    HumanitarianReportEntity,
    IndustryRiskRollup,
    Job,
    LLMRun,
    MacroObservation,
    MacroSeries,
    MacroSignalSnapshot,
    ProviderRun,
    RawDocumentAsset,
    RawIngestionItem,
    Report,
    ReportSection,
    RiskScoreObservation,
    RiskWarning,
    SanctionsAlias,
    SanctionsEntity,
    SanctionsIdentifier,
    SanctionsList,
    SanctionsMatch,
    SavedSearch,
    SECCompany,
    SECCompanyFact,
    SECFiling,
    Security,
    Source,
    SourceCursor,
    SourceHealthSnapshot,
    User,
    WatchlistItem,
)
from db.models.enums import Horizon, RiskLevel, RiskType, SourceType, risk_level_for_score
from db.models.pipeline import PipelineRunDetail
from db.models.risk import (
    CountryDailyRiskSignal,
    CrisisPrediction,
    CrisisPredictionEvaluation,
    EventRiskFeature,
)

# Order is illustrative; create_all/drop_all resolve FK dependencies automatically.
STAGE2_TABLES = (
    Source,
    Article,
    ArticleEmbedding,
    Event,
    EventArticle,
    LLMRun,
    Job,
    CountryDailyRiskSignal,
    EventRiskFeature,
    CrisisPrediction,
    CrisisPredictionEvaluation,
)

PROVIDER_DATA_TABLES = (
    ProviderRun,
    SourceCursor,
    RawIngestionItem,
    MacroSeries,
    MacroObservation,
    MacroSignalSnapshot,
    SECCompany,
    SECFiling,
    SECCompanyFact,
)

PROVIDER_EXPANSION_TABLES = (
    SanctionsList,
    SanctionsEntity,
    SanctionsAlias,
    SanctionsIdentifier,
    SanctionsMatch,
    EntityProfile,
    EntityIdentifier,
    EntityRelationship,
    EntityResolutionRun,
    CountryIndicatorSeries,
    CountryIndicatorObservation,
    CountryContextSnapshot,
    HumanitarianReport,
    HumanitarianReportEntity,
    GeoIncident,
    GeoIncidentImpact,
    EnergyMarketSnapshot,
    EnergyDisruptionEvent,
)

# Tables introduced by the Stage 1 intelligence-contract migration (0013). Ordered so that
# FK dependencies are created before their dependents.
STAGE1_INTELLIGENCE_TABLES = (
    EntityAlias,
    EntityRedirect,
    HistoricalEpisode,
    ForecastScenario,
    EventAnalogy,
    RiskWarning,
)

COMPANY_MASTER_TABLES = (
    Company,
    CompanyAlias,
    CompanyIdentifier,
    Security,
)

INGESTION_OBSERVABILITY_TABLES = (
    SourceHealthSnapshot,
    RawDocumentAsset,
)

EVIDENCE_TABLES = (
    EvidenceItem,
    Claim,
    ClaimEvidence,
)

EVENT_INTELLIGENCE_TABLES = (
    EventEmbedding,
    EventEntity,
    EventCompany,
    EventIndustry,
    EventTimelineItem,
    EventLocation,
    GeocodingCache,
)

RISK_OUTPUT_TABLES = (
    RiskScoreObservation,
    CompanyRiskRollup,
    IndustryRiskRollup,
    DailyIntelligenceSummary,
)

APPLICATION_TABLES = (
    User,
    WatchlistItem,
    AlertRule,
    Alert,
    Report,
    ReportSection,
    SavedSearch,
)

__all__ = [
    "ACTIVE_ALERT_STATES",
    "ALERT_STATES",
    "APPLICATION_TABLES",
    "Alert",
    "AlertConditionState",
    "AlertRule",
    "Claim",
    "ClaimEvidence",
    "COMPANY_MASTER_TABLES",
    "EMBEDDING_DIM",
    "EMBEDDING_MODEL",
    "EMBEDDING_MODEL_VERSION",
    "EVENT_INTELLIGENCE_TABLES",
    "EVIDENCE_TABLES",
    "INGESTION_OBSERVABILITY_TABLES",
    "PROVIDER_DATA_TABLES",
    "PROVIDER_EXPANSION_TABLES",
    "PipelineRunDetail",
    "REPORT_CONTENT_POLICY_DESCRIPTIVE_ONLY",
    "REPORT_CONTENT_POLICY_PREDICTION_BACKED",
    "RISK_OUTPUT_TABLES",
    "STAGE1_INTELLIGENCE_TABLES",
    "STAGE2_TABLES",
    "Article",
    "ArticleEmbedding",
    "Company",
    "CompanyAlias",
    "CompanyIdentifier",
    "CompanyRiskRollup",
    "CountryContextSnapshot",
    "CountryDailyRiskSignal",
    "CountryIndicatorObservation",
    "CountryIndicatorSeries",
    "CrisisPrediction",
    "CrisisPredictionEvaluation",
    "DailyIntelligenceSummary",
    "EnergyDisruptionEvent",
    "EnergyMarketSnapshot",
    "EntityAlias",
    "EntityIdentifier",
    "EntityProfile",
    "EntityRedirect",
    "EntityRelationship",
    "EntityResolutionRun",
    "Event",
    "EventAnalogy",
    "EventArticle",
    "EventCompany",
    "EventEmbedding",
    "EventEntity",
    "EventIndustry",
    "EventLocation",
    "EventRiskFeature",
    "EventTimelineItem",
    "EvidenceItem",
    "ForecastScenario",
    "GeocodingCache",
    "GeoIncident",
    "GeoIncidentImpact",
    "HistoricalEpisode",
    "HistoricalEpisodeEmbedding",
    "Horizon",
    "HumanitarianReport",
    "HumanitarianReportEntity",
    "IndustryRiskRollup",
    "Job",
    "LLMRun",
    "MacroObservation",
    "MacroSeries",
    "MacroSignalSnapshot",
    "ProviderRun",
    "RawDocumentAsset",
    "RawIngestionItem",
    "Report",
    "ReportSection",
    "RiskScoreObservation",
    "RiskLevel",
    "RiskType",
    "RiskWarning",
    "SECCompany",
    "SECCompanyFact",
    "SECFiling",
    "SanctionsAlias",
    "SanctionsEntity",
    "SanctionsIdentifier",
    "SanctionsList",
    "SanctionsMatch",
    "SavedSearch",
    "Security",
    "Source",
    "SourceCursor",
    "SourceHealthSnapshot",
    "SourceType",
    "User",
    "WatchlistItem",
    "risk_level_for_score",
]
