"""Deterministic alert-policy primitives (ADR 0010).

Pure functions and value objects: severity hysteresis, lifecycle transitions, velocity
persistence, `what_could_reduce_risk` predicates, the `news_driven` contribution, and the
dedupe key. Nothing here touches the database, the network, or the clock -- callers pass
`now` and the persisted state in, and persist the returned decision themselves.
"""

from services.alerts.budget import (
    ACTIVE_BUDGET,
    BudgetOutcome,
    BudgetOutcomeKind,
    BudgetRepository,
    LifecycleSnapshot,
    alert_rank,
    enforce_budget,
    weakest,
)
from services.alerts.contribution import news_driven_contribution
from services.alerts.dedupe import DEDUPE_KEY_MAX_LENGTH, DedupeKey, build_dedupe_key
from services.alerts.experimental import (
    REQUIRED_WINDOWS,
    ExperimentalGate,
    GateDecision,
    GateEvidenceError,
    ScoreBasis,
    WindowEvidence,
)
from services.alerts.hysteresis import (
    CLEAR_THRESHOLD,
    ENTER_THRESHOLD,
    HYSTERESIS_MARGIN,
    RESOLVE_CLEAR_THRESHOLD,
    SEVERITY_ORDER,
    applicable_clear_threshold,
    canonical_severity,
    is_below_clear_band,
    next_severity,
    severity_rank,
)
from services.alerts.lifecycle import (
    ACTIVE_STATES,
    RESOLVE_AFTER,
    AlertLifecycleState,
    AlertState,
    LifecycleDecision,
    LifecycleTrigger,
    decide_lifecycle,
)
from services.alerts.notifications import (
    ACKNOWLEDGED_KINDS,
    AlertAcknowledger,
    AlertActionKind,
    AlertNotifier,
    DeliveryReport,
    LoggingAlertNotifier,
    NotifierDeliveryError,
    PendingAlertAction,
    RecordingAlertNotifier,
    deliver_actions,
)
from services.alerts.reduction import (
    Comparator,
    ManualReviewCondition,
    ReductionAssessment,
    ReductionCondition,
    ReductionOutcome,
    ReductionPredicate,
    ReductionStatus,
    evaluate_reduction_conditions,
    parse_reduction_conditions,
)
from services.alerts.repository import (
    AlertDedupeConflictError,
    AlertPersistenceError,
    AlertRepository,
    AlertStateCorruptionError,
    InMemoryAlertRepository,
    SQLAlchemyAlertRepository,
)
from services.alerts.service import (
    COOLDOWN,
    AlertLifecycleService,
    AlertObservation,
    AlertOutcome,
    AlertOutcomeKind,
    AlertScope,
    ConditionKind,
    StaleObservationError,
)
from services.alerts.supersession import (
    SupersessionError,
    SupersessionRepository,
    SupersessionResult,
    supersede,
    supersede_with_broader_alert,
    supersession_action,
)
from services.alerts.velocity import (
    VELOCITY_REQUIRED_RUNS,
    VELOCITY_Z_THRESHOLD,
    VelocityDecision,
    decide_velocity_persistence,
)

__all__ = [
    "ACKNOWLEDGED_KINDS",
    "ACTIVE_BUDGET",
    "ACTIVE_STATES",
    "CLEAR_THRESHOLD",
    "COOLDOWN",
    "DEDUPE_KEY_MAX_LENGTH",
    "ENTER_THRESHOLD",
    "HYSTERESIS_MARGIN",
    "REQUIRED_WINDOWS",
    "RESOLVE_AFTER",
    "RESOLVE_CLEAR_THRESHOLD",
    "SEVERITY_ORDER",
    "VELOCITY_REQUIRED_RUNS",
    "VELOCITY_Z_THRESHOLD",
    "AlertAcknowledger",
    "AlertActionKind",
    "AlertDedupeConflictError",
    "AlertLifecycleService",
    "AlertLifecycleState",
    "AlertNotifier",
    "AlertObservation",
    "AlertOutcome",
    "AlertOutcomeKind",
    "AlertPersistenceError",
    "AlertRepository",
    "AlertScope",
    "AlertState",
    "AlertStateCorruptionError",
    "BudgetOutcome",
    "BudgetOutcomeKind",
    "BudgetRepository",
    "Comparator",
    "ConditionKind",
    "DedupeKey",
    "DeliveryReport",
    "ExperimentalGate",
    "GateDecision",
    "GateEvidenceError",
    "InMemoryAlertRepository",
    "LifecycleDecision",
    "LifecycleSnapshot",
    "LifecycleTrigger",
    "LoggingAlertNotifier",
    "ManualReviewCondition",
    "NotifierDeliveryError",
    "PendingAlertAction",
    "RecordingAlertNotifier",
    "ReductionAssessment",
    "ReductionCondition",
    "ReductionOutcome",
    "ReductionPredicate",
    "ReductionStatus",
    "SQLAlchemyAlertRepository",
    "ScoreBasis",
    "StaleObservationError",
    "SupersessionError",
    "SupersessionRepository",
    "SupersessionResult",
    "VelocityDecision",
    "WindowEvidence",
    "alert_rank",
    "applicable_clear_threshold",
    "build_dedupe_key",
    "canonical_severity",
    "decide_lifecycle",
    "decide_velocity_persistence",
    "deliver_actions",
    "enforce_budget",
    "evaluate_reduction_conditions",
    "is_below_clear_band",
    "news_driven_contribution",
    "next_severity",
    "parse_reduction_conditions",
    "severity_rank",
    "supersede",
    "supersede_with_broader_alert",
    "supersession_action",
    "weakest",
]
