"""Public exports for the `services.llm` package."""

from db.models.core import Job
from services.llm.adapters import (
    LLMInvocationMode,
    LLMInvocationRequest,
    LLMInvocationResponse,
    LLMProviderAdapter,
    SupportsStructuredJSON,
)
from services.llm.cache import InMemoryLLMPromptCache, PromptCache, RedisLLMPromptCache
from services.llm.contracts import (
    NIL_DECISION,
    BaseLLMContract,
    Critique,
    CritiqueVerdict,
    EntityLinkAdjudication,
    EventExtraction,
    ForecastScenarios,
    ImpactDirection,
    IndustryImpact,
    LLMContractConfigurationError,
    LLMContractLookupError,
    ReportComposition,
    list_contract_schemas,
    validate_llm_contract_payload,
    validate_llm_payload,
)
from services.llm.http_providers import (
    AnthropicMessagesProvider,
    DeepSeekChatCompletionsProvider,
    GeminiInteractionsProvider,
    LLMBatchModeUnsupported,
    LLMProviderError,
    LLMProviderOutputError,
    LLMRetryableProviderOutputError,
    OpenAIChatCompletionsProvider,
    build_provider_for_tier,
    build_providers_by_tier,
)
from services.llm.limiter import (
    CompositeProviderLimiter,
    InMemoryTokenBucketLimiter,
    RedisTokenBucketLimiter,
    TokenBucketLimiter,
    build_provider_rate_limiter,
)
from services.llm.policy import (
    CALLABLE_TIERS,
    LLMBudgetPolicy,
    LLMRoutingContext,
    LLMRoutingDecision,
    LLMTier,
    resolve_tier_model,
)
from services.llm.pricing import estimate_completion_cost_usd
from services.llm.repository import (
    InMemoryLLMRuntimeRepository,
    LLMRuntimeRepository,
    SQLAlchemyLLMRuntimeRepository,
)
from services.llm.runtime import build_production_orchestrator
from services.llm.selection import (
    RepresentativeArticleSelection,
    estimate_token_count,
    select_representative_articles,
)

__all__ = [
    "CALLABLE_TIERS",
    "NIL_DECISION",
    "AnthropicMessagesProvider",
    "BaseLLMContract",
    "CompositeProviderLimiter",
    "DeepSeekChatCompletionsProvider",
    "EntityLinkAdjudication",
    "GeminiInteractionsProvider",
    "InMemoryLLMRuntimeRepository",
    "InMemoryTokenBucketLimiter",
    "LLMBatchModeUnsupported",
    "LLMBudgetPolicy",
    "LLMProviderError",
    "LLMProviderOutputError",
    "LLMRetryableProviderOutputError",
    "LLMRoutingContext",
    "LLMRoutingDecision",
    "LLMRuntimeRepository",
    "SQLAlchemyLLMRuntimeRepository",
    "LLMTier",
    "Job",
    "Critique",
    "CritiqueVerdict",
    "EventExtraction",
    "ForecastScenarios",
    "InMemoryLLMPromptCache",
    "ImpactDirection",
    "IndustryImpact",
    "LLMContractConfigurationError",
    "LLMContractLookupError",
    "LLMInvocationMode",
    "LLMInvocationRequest",
    "LLMInvocationResponse",
    "LLMProviderAdapter",
    "OpenAIChatCompletionsProvider",
    "PromptCache",
    "RedisLLMPromptCache",
    "RedisTokenBucketLimiter",
    "RepresentativeArticleSelection",
    "ReportComposition",
    "SupportsStructuredJSON",
    "TokenBucketLimiter",
    "build_provider_for_tier",
    "build_production_orchestrator",
    "build_provider_rate_limiter",
    "build_providers_by_tier",
    "estimate_completion_cost_usd",
    "estimate_token_count",
    "list_contract_schemas",
    "resolve_tier_model",
    "select_representative_articles",
    "validate_llm_contract_payload",
    "validate_llm_payload",
]
