"""Provider contracts and deterministic fake implementations."""

from packages.providers.base import (
    Clock,
    CountryIndicator,
    CountryIndicatorObservation,
    CountryIndicatorProvider,
    EmbeddingProvider,
    EmbeddingResult,
    EnergyObservation,
    EnergyProvider,
    EnergySeries,
    EntityIdentityProvider,
    FREDObservation,
    FREDProvider,
    GDELTArticle,
    GDELTEvent,
    GDELTProvider,
    GeoIncident,
    GeoIncidentProvider,
    HumanitarianProvider,
    HumanitarianReport,
    LEIRecord,
    LEIRelationship,
    LLMProvider,
    LLMResponse,
    RSSItem,
    RSSProvider,
    SanctionsAlias,
    SanctionsDelta,
    SanctionsEntity,
    SanctionsIdentifier,
    SanctionsProvider,
    SECCompanyFact,
    SECEdgarProvider,
    SECSubmission,
    SystemClock,
)
from packages.providers.eia import EIAClient
from packages.providers.fakes import (
    FakeEmbeddingProvider,
    FakeEnergyProvider,
    FakeEntityIdentityProvider,
    FakeFREDProvider,
    FakeGDELTProvider,
    FakeGeoIncidentProvider,
    FakeHumanitarianProvider,
    FakeLLMProvider,
    FakeRSSProvider,
    FakeSanctionsProvider,
    FakeSECEdgarProvider,
    FixedClock,
)
from packages.providers.fred import FREDClient
from packages.providers.gdelt import GDELTClient
from packages.providers.gleif import GLEIFClient
from packages.providers.nasa_firms import NASAFIRMSClient
from packages.providers.ofac import OFACClient
from packages.providers.reliefweb import ReliefWebClient
from packages.providers.sec_edgar import SECEdgarClient
from packages.providers.usgs import USGSEarthquakeClient
from packages.providers.world_bank import WorldBankClient

__all__ = [
    "Clock",
    "CountryIndicator",
    "CountryIndicatorObservation",
    "CountryIndicatorProvider",
    "EIAClient",
    "EmbeddingProvider",
    "EmbeddingResult",
    "EnergyObservation",
    "EnergyProvider",
    "EnergySeries",
    "EntityIdentityProvider",
    "FREDClient",
    "FREDObservation",
    "FREDProvider",
    "FakeEmbeddingProvider",
    "FakeEnergyProvider",
    "FakeEntityIdentityProvider",
    "FakeFREDProvider",
    "FakeGDELTProvider",
    "FakeGeoIncidentProvider",
    "FakeHumanitarianProvider",
    "FakeLLMProvider",
    "FakeRSSProvider",
    "FakeSanctionsProvider",
    "FakeSECEdgarProvider",
    "FixedClock",
    "GDELTArticle",
    "GDELTClient",
    "GDELTEvent",
    "GDELTProvider",
    "GLEIFClient",
    "GeoIncident",
    "GeoIncidentProvider",
    "HumanitarianProvider",
    "HumanitarianReport",
    "LEIRecord",
    "LEIRelationship",
    "LLMProvider",
    "LLMResponse",
    "NASAFIRMSClient",
    "OFACClient",
    "RSSItem",
    "RSSProvider",
    "ReliefWebClient",
    "SanctionsAlias",
    "SanctionsDelta",
    "SanctionsEntity",
    "SanctionsIdentifier",
    "SanctionsProvider",
    "SECCompanyFact",
    "SECEdgarClient",
    "SECEdgarProvider",
    "SECSubmission",
    "SystemClock",
    "USGSEarthquakeClient",
    "WorldBankClient",
]
