"""Deterministic inputs and composition context for the daily brief (ADR 0009, spec).

Stage 6, deterministic half: *what goes in the brief*, and *what may be said about it*. Given a
window, this package selects the Top Events, the executive summary's inputs, the risk radar and
its day-over-day comparison, yesterday's published brief; loads the evidence, historical-parallel
and forecast context for the selected events; and lays out the brief's section skeleton -- and
stops there.

It does not compose. No prose, no LLM, no grounding gate, no persistence, no API, no export;
those are the composition stage's, and the seam between them is :class:`BriefInputs`,
:class:`BriefContext`, and :class:`BriefMaterial`.

Layering, and the reason for it:

- :mod:`services.reports.window`, :mod:`services.reports.contracts`, and
  :mod:`services.reports.context` are pure values, importing no SQLAlchemy.
- :mod:`services.reports.selection` and the pure builders in :mod:`services.reports.context`
  and :mod:`services.reports.material` hold every policy decision -- the hotness floor, the
  0.6/0.4 ranking, what counts as supportive evidence, which scenario set is current, the
  section order -- as pure functions over rows. All of it is testable against hand-built rows
  with no database in sight.
- :mod:`services.reports.repository` and :mod:`services.reports.context_repository` are the only
  modules that know SQL, and they decide nothing: they load, bounded and deterministically,
  through the :class:`BriefInputRepository` and :class:`BriefContextRepository` protocols.

The event hotness score the ranking depends on is *not* here: it is a clustering feature
(`services.nlp.features.event_hotness_score`), written to `events.hotness_score` as clusters
form, and this package only reads it.
"""

from services.reports.composition import (
    COMPOSITION_JOB_TYPE,
    COMPOSITION_RISK_LEVEL,
    COMPOSITION_TEMPERATURE,
    COMPOSITION_TIER,
    EXECUTIVE_SUMMARY_BUDGET,
    HISTORICAL_PARALLELS_BUDGET,
    RISK_COMMENTARY_BUDGET,
    TOP_EVENT_BUDGET,
    BriefDraft,
    BudgetOutcome,
    CompositionAttempt,
    DraftBlock,
    DraftDegradationCode,
    DraftSection,
    ReportCompositionError,
    SectionDegradation,
    WordBudget,
    compose_brief,
    compose_section,
    composition_job,
    count_words,
)
from services.reports.consistency import (
    ConsistencyFinding,
    brief_reversals,
    check_reversal_acknowledgement,
    reversal_marker,
)
from services.reports.context import (
    ARTICLE_EVIDENCE_SOURCE_TYPE,
    MAX_ANALOGIES_PER_EVENT,
    MAX_CLAIMS_PER_EVENT,
    MAX_EXCERPT_CHARS,
    MAX_LINKS_PER_CLAIM,
    PROBABILITY_SUM,
    PROBABILITY_TOLERANCE,
    REQUIRED_SCENARIO_NAMES,
    SUPPORTIVE_SUPPORT_TYPES,
    AnalogyContext,
    BoundedRead,
    BriefContext,
    BriefContextRepository,
    ClaimContext,
    EventAnalogyContext,
    EventEvidenceContext,
    EventForecast,
    EvidenceArticle,
    EvidenceLink,
    EvidenceRow,
    ExcerptOrigin,
    ForecastScenarioRow,
    HistoricalOnset,
    HistoricalOutcomeContext,
    ImmutableJSON,
    ParentEpisode,
    SourceExcerpt,
    build_analogy_context,
    build_brief_context,
    build_evidence_context,
    build_source_excerpt,
    freeze_json,
    is_supportive,
    select_event_forecasts,
)
from services.reports.context_repository import SQLAlchemyBriefContextRepository
from services.reports.contracts import (
    BRIEF_SEVERITIES,
    PROVENANCE_PRECEDENCE,
    AlertStateChange,
    BriefInputRepository,
    BriefInputs,
    DataQuality,
    DataQualityNote,
    EventWindowRow,
    ExecutiveSummaryInputs,
    LinkedRisk,
    PriorBriefContext,
    PriorBriefSection,
    PriorBriefVersion,
    RiskKey,
    RiskMove,
    RiskObservationRow,
    RiskProvenance,
    RiskRadar,
    RiskRadarEntry,
    SelectedEvent,
)
from services.reports.copyright import (
    MAX_CONSECUTIVE_WORDS,
    MAX_QUOTE_WORDS,
    CopyrightFinding,
    CopyrightViolation,
    SnippetSource,
    check_block_copyright,
    normalize_words,
)
from services.reports.generation import (
    DEFAULT_CHANGE_REASON,
    DailyBriefGenerationError,
    DailyBriefGenerationResult,
    build_generation_orchestrator_factory,
    generate_daily_brief,
)
from services.reports.grounding import (
    GROUNDING_JOB_TYPE,
    GROUNDING_RISK_LEVEL,
    GROUNDING_TEMPERATURE,
    GROUNDING_TIER,
    MAX_CLAIM_LOSS_RATIO,
    ClaimVerdict,
    GateOutcome,
    GroundingAttempt,
    GroundingGateResult,
    SectionGroundingResult,
    SectionGroundingStatus,
    grounding_job,
    run_grounding_gate,
)
from services.reports.grounding_prompts import (
    GROUNDING_PROMPT_NAME,
    GROUNDING_PROMPT_TEMPLATE_VERSION,
    GROUNDING_PROMPT_VERSION,
    GROUNDING_SCHEMA,
    GROUNDING_SCHEMA_VERSION,
    build_grounding_prompt,
)
from services.reports.lifecycle import (
    LEGAL_TRANSITIONS,
    PUBLISHABLE_SECTION_STATUSES,
    STALE_SCAN_LIMIT,
    TERMINAL_STATUSES,
    VERSION_LIST_LIMIT,
    CannotPublishError,
    ChangeReasonRequiredError,
    GeneratedByRunIdConflictError,
    IllegalTransitionError,
    ReportLifecycleError,
    ReportLifecycleRepository,
    ReportNotFoundError,
    ReportSectionRow,
    ReportSectionSnapshot,
    ReportSnapshot,
    ReportStatus,
    ReportVersionConflictError,
    SectionBlock,
    SectionsAlreadyWrittenError,
    SectionValidationError,
    StaleScanOverflowError,
    default_daily_brief_title,
    generated_by_run_id_for,
    persist_daily_brief,
    section_rows_from_gate,
    validate_transition,
)
from services.reports.material import (
    FINAL_DISCLAIMER,
    MAX_TOP_EVENT_SECTIONS,
    SECTION_ORDER,
    AlertRow,
    BriefMaterial,
    ChangeRow,
    ForecastRow,
    RiskRadarRow,
    SectionKind,
    SectionMaterial,
    build_brief_material,
)
from services.reports.prompts import (
    COMPOSITION_PROMPT_TEMPLATE_VERSION,
    COMPOSITION_PROMPT_VERSION,
    COMPOSITION_SCHEMA,
    COMPOSITION_SCHEMA_VERSION,
    EXECUTIVE_SUMMARY_PROMPT_NAME,
    HISTORICAL_PARALLELS_PROMPT_NAME,
    PRIOR_BRIEF_BODY_CHARS,
    PRIOR_BRIEF_MAX_KEY_CLAIMS,
    PRIOR_BRIEF_MAX_SECTIONS,
    PRIOR_BRIEF_TRUNCATION_MARKER,
    RISK_COMMENTARY_PROMPT_NAME,
    TOP_EVENT_PROMPT_NAME,
    budget_feedback,
    build_executive_summary_prompt,
    build_historical_parallels_prompt,
    build_risk_commentary_prompt,
    build_top_event_prompt,
    claim_record,
)
from services.reports.repository import (
    DAILY_BRIEF_REPORT_TYPE,
    EVENT_RISK_TARGET_TYPE,
    RADAR_LOOKBACK,
    SQLAlchemyBriefInputRepository,
)
from services.reports.selection import (
    EXEC_SUMMARY_EVENT_COUNT,
    HOTNESS_FLOOR,
    HOTNESS_WEIGHT,
    LINKED_RISK_WEIGHT,
    PUBLISHED_STATUS,
    TOP_EVENT_COUNT,
    build_brief_inputs,
    build_risk_radar,
    largest_risk_move,
    pick_published_version,
    ranking_score,
    resolve_linked_risk,
    select_alert_state_changes,
    select_top_events,
)
from services.reports.window import (
    BRIEF_CUTOFF_HOUR,
    BRIEF_CUTOFF_MINUTE,
    BRIEF_TIMEZONE,
    BriefWindow,
    NaiveDatetimeError,
    cutoff_for,
    window_for,
    window_for_date,
)

__all__ = [
    "ARTICLE_EVIDENCE_SOURCE_TYPE",
    "BRIEF_CUTOFF_HOUR",
    "BRIEF_CUTOFF_MINUTE",
    "BRIEF_SEVERITIES",
    "BRIEF_TIMEZONE",
    "COMPOSITION_JOB_TYPE",
    "COMPOSITION_PROMPT_TEMPLATE_VERSION",
    "COMPOSITION_PROMPT_VERSION",
    "COMPOSITION_RISK_LEVEL",
    "COMPOSITION_SCHEMA",
    "COMPOSITION_SCHEMA_VERSION",
    "COMPOSITION_TEMPERATURE",
    "COMPOSITION_TIER",
    "DAILY_BRIEF_REPORT_TYPE",
    "DEFAULT_CHANGE_REASON",
    "EVENT_RISK_TARGET_TYPE",
    "EXEC_SUMMARY_EVENT_COUNT",
    "EXECUTIVE_SUMMARY_BUDGET",
    "EXECUTIVE_SUMMARY_PROMPT_NAME",
    "FINAL_DISCLAIMER",
    "GROUNDING_JOB_TYPE",
    "GROUNDING_PROMPT_NAME",
    "GROUNDING_PROMPT_TEMPLATE_VERSION",
    "GROUNDING_PROMPT_VERSION",
    "GROUNDING_RISK_LEVEL",
    "GROUNDING_SCHEMA",
    "GROUNDING_SCHEMA_VERSION",
    "GROUNDING_TEMPERATURE",
    "GROUNDING_TIER",
    "HISTORICAL_PARALLELS_BUDGET",
    "HISTORICAL_PARALLELS_PROMPT_NAME",
    "HOTNESS_FLOOR",
    "HOTNESS_WEIGHT",
    "LEGAL_TRANSITIONS",
    "LINKED_RISK_WEIGHT",
    "MAX_ANALOGIES_PER_EVENT",
    "MAX_CLAIM_LOSS_RATIO",
    "MAX_CLAIMS_PER_EVENT",
    "MAX_CONSECUTIVE_WORDS",
    "MAX_EXCERPT_CHARS",
    "MAX_LINKS_PER_CLAIM",
    "MAX_QUOTE_WORDS",
    "MAX_TOP_EVENT_SECTIONS",
    "PRIOR_BRIEF_BODY_CHARS",
    "PRIOR_BRIEF_MAX_KEY_CLAIMS",
    "PRIOR_BRIEF_MAX_SECTIONS",
    "PRIOR_BRIEF_TRUNCATION_MARKER",
    "PROBABILITY_SUM",
    "PROBABILITY_TOLERANCE",
    "PROVENANCE_PRECEDENCE",
    "PUBLISHABLE_SECTION_STATUSES",
    "PUBLISHED_STATUS",
    "RADAR_LOOKBACK",
    "REQUIRED_SCENARIO_NAMES",
    "RISK_COMMENTARY_BUDGET",
    "RISK_COMMENTARY_PROMPT_NAME",
    "SECTION_ORDER",
    "STALE_SCAN_LIMIT",
    "SUPPORTIVE_SUPPORT_TYPES",
    "TERMINAL_STATUSES",
    "TOP_EVENT_BUDGET",
    "TOP_EVENT_COUNT",
    "TOP_EVENT_PROMPT_NAME",
    "VERSION_LIST_LIMIT",
    "AlertRow",
    "AlertStateChange",
    "AnalogyContext",
    "BoundedRead",
    "BriefContext",
    "BriefContextRepository",
    "BriefDraft",
    "BriefInputRepository",
    "BriefInputs",
    "BriefMaterial",
    "BriefWindow",
    "BudgetOutcome",
    "CannotPublishError",
    "ChangeReasonRequiredError",
    "ChangeRow",
    "ClaimContext",
    "ClaimVerdict",
    "CompositionAttempt",
    "ConsistencyFinding",
    "CopyrightFinding",
    "CopyrightViolation",
    "DailyBriefGenerationError",
    "DailyBriefGenerationResult",
    "DataQuality",
    "DataQualityNote",
    "DraftBlock",
    "DraftDegradationCode",
    "DraftSection",
    "EventAnalogyContext",
    "EventEvidenceContext",
    "EventForecast",
    "EventWindowRow",
    "EvidenceArticle",
    "EvidenceLink",
    "EvidenceRow",
    "ExcerptOrigin",
    "ExecutiveSummaryInputs",
    "ForecastRow",
    "ForecastScenarioRow",
    "GateOutcome",
    "GeneratedByRunIdConflictError",
    "GroundingAttempt",
    "GroundingGateResult",
    "HistoricalOnset",
    "HistoricalOutcomeContext",
    "IllegalTransitionError",
    "ImmutableJSON",
    "LinkedRisk",
    "NaiveDatetimeError",
    "ParentEpisode",
    "PriorBriefContext",
    "PriorBriefSection",
    "PriorBriefVersion",
    "ReportCompositionError",
    "ReportLifecycleError",
    "ReportLifecycleRepository",
    "ReportNotFoundError",
    "ReportSectionRow",
    "ReportSectionSnapshot",
    "ReportSnapshot",
    "ReportStatus",
    "ReportVersionConflictError",
    "RiskKey",
    "RiskMove",
    "RiskObservationRow",
    "RiskProvenance",
    "RiskRadar",
    "RiskRadarEntry",
    "RiskRadarRow",
    "SQLAlchemyBriefContextRepository",
    "SQLAlchemyBriefInputRepository",
    "SectionBlock",
    "SectionDegradation",
    "SectionGroundingResult",
    "SectionGroundingStatus",
    "SectionKind",
    "SectionMaterial",
    "SectionValidationError",
    "SectionsAlreadyWrittenError",
    "SelectedEvent",
    "SnippetSource",
    "SourceExcerpt",
    "StaleScanOverflowError",
    "WordBudget",
    "brief_reversals",
    "budget_feedback",
    "build_analogy_context",
    "build_generation_orchestrator_factory",
    "build_brief_context",
    "build_brief_inputs",
    "build_brief_material",
    "build_evidence_context",
    "build_executive_summary_prompt",
    "build_grounding_prompt",
    "build_historical_parallels_prompt",
    "build_risk_commentary_prompt",
    "build_risk_radar",
    "build_source_excerpt",
    "build_top_event_prompt",
    "check_block_copyright",
    "check_reversal_acknowledgement",
    "claim_record",
    "compose_brief",
    "compose_section",
    "composition_job",
    "count_words",
    "cutoff_for",
    "default_daily_brief_title",
    "freeze_json",
    "generate_daily_brief",
    "generated_by_run_id_for",
    "grounding_job",
    "is_supportive",
    "largest_risk_move",
    "normalize_words",
    "persist_daily_brief",
    "pick_published_version",
    "ranking_score",
    "resolve_linked_risk",
    "reversal_marker",
    "run_grounding_gate",
    "section_rows_from_gate",
    "select_alert_state_changes",
    "select_event_forecasts",
    "select_top_events",
    "validate_transition",
    "window_for",
    "window_for_date",
]
