"""The daily brief's deterministic section material (report-generation spec, ADR 0009).

The last purely deterministic step before composition. Given the selected inputs
(:class:`~services.reports.contracts.BriefInputs`) and the loaded context
(:class:`~services.reports.context.BriefContext`), this module lays out *the brief's skeleton*:
which sections exist, in what order, and -- for the sections that are tables rather than prose --
their exact rows.

What this module does not do is the whole point of it:

* **It writes no prose.** Every section except the disclaimer is a placeholder; ``prose`` is
  empty and the composer fills it. A deterministic layer that "helpfully" wrote a sentence would
  be writing an unattributed, ungrounded sentence, and the grounding gate has no way to check a
  sentence nothing generated.
* **It claims no grounding.** Material carries claim ids so the composer can cite them; it does
  not assert that anything is supported by them. Support is the gate's verdict, not this
  module's.

Two structural rules hold on every brief this module can produce, quiet or busy:

* **What Changed Since Yesterday is always present.** The spec calls it the section users trust
  most, and a brief that silently dropped it on the day nothing could be compared would be
  hiding exactly the fact the reader needs. When the comparison cannot be made, the section says
  so.
* **The disclaimer is always last.** :data:`FINAL_DISCLAIMER` is fixed text, reproduced verbatim
  in every brief and every export (spec, S23.2).
"""

from __future__ import annotations

import datetime
import uuid
from collections.abc import Sequence
from dataclasses import dataclass, field
from enum import StrEnum

from services.reports.context import (
    AnalogyContext,
    BriefContext,
    EventEvidenceContext,
    EventForecast,
    ImmutableJSON,
    freeze_json,
)
from services.reports.contracts import (
    AlertStateChange,
    BriefInputs,
    DataQuality,
    DataQualityNote,
    RiskKey,
    SelectedEvent,
)

#: The exact, immutable financial disclaimer (report-generation spec, S23.2). Reproduced
#: verbatim in every brief and every export; it is a fixed template block, never composed, never
#: paraphrased, and never regenerated by a model.
FINAL_DISCLAIMER = (
    "This system provides probabilistic analysis based on public information, data signals, "
    "and model-assisted reasoning. It is for informational purposes only and does not "
    "constitute investment, legal, or financial advice."
)


class SectionKind(StrEnum):
    """Every section a daily brief can contain. There is no Watchlist: it is deferred to
    Phase 6 (report-generation spec) because it is per-user and the brief is a global artifact.
    """

    EXECUTIVE_SUMMARY = "executive_summary"
    TOP_EVENT = "top_event"
    RISK_RADAR = "risk_radar"
    HISTORICAL_PARALLELS = "historical_parallels"
    FORECASTS = "forecasts"
    ALERTS = "alerts"
    WHAT_CHANGED = "what_changed"
    DATA_QUALITY = "data_quality"
    DISCLAIMER = "disclaimer"


#: The brief's stable reading order: the lede, then the stories, then the standing tables, then
#: what we could not see, then the disclaimer. Fixed rather than derived, so that a reader who
#: opens Tuesday's brief finds Monday's structure -- and so that a section cannot be reordered
#: into a position that changes what it appears to claim.
SECTION_ORDER: tuple[SectionKind, ...] = (
    SectionKind.EXECUTIVE_SUMMARY,
    SectionKind.TOP_EVENT,
    SectionKind.RISK_RADAR,
    SectionKind.HISTORICAL_PARALLELS,
    SectionKind.FORECASTS,
    SectionKind.ALERTS,
    SectionKind.WHAT_CHANGED,
    SectionKind.DATA_QUALITY,
    SectionKind.DISCLAIMER,
)

#: "take top 5" (report-generation spec). Zero on a quiet day: the section shrinks, never pads.
MAX_TOP_EVENT_SECTIONS = 5


# --------------------------------------------------------------------------------------
# Structured rows
# --------------------------------------------------------------------------------------


@dataclass(frozen=True)
class RiskRadarRow:
    """One risk's standing score, and its movement if it can be measured."""

    key: RiskKey
    score: float
    level: str
    as_of: datetime.datetime
    previous_score: float | None
    previous_level: str | None
    #: Signed: positive is a risk that rose, negative one that eased. ``None`` when the risk was
    #: first observed inside this window and so has no prior score to move from -- which is not
    #: a move of zero, and is not a jump from zero either.
    delta: float | None
    is_reversal: bool

    @property
    def comparison_available(self) -> bool:
        return self.previous_level is not None


@dataclass(frozen=True)
class ForecastRow:
    """One scenario of one event's current MECE set. Table only -- never narrated here."""

    event_id: uuid.UUID
    event_title: str
    scenario_set_id: uuid.UUID
    scenario_name: str
    probability: float
    risk_score: float
    severity: str
    horizon: str
    confidence: float | None
    #: Provenance JSON, deep-frozen on construction (:func:`freeze_json`). Its source -- a
    #: :class:`ForecastScenarioRow` -- is already frozen; this re-freeze keeps the guarantee
    #: local to the material row and holds even if a caller builds one by hand.
    evidence_refs: ImmutableJSON | None

    def __post_init__(self) -> None:
        object.__setattr__(self, "evidence_refs", freeze_json(self.evidence_refs))


@dataclass(frozen=True)
class AlertRow:
    """One alert state change. List only."""

    alert_id: uuid.UUID
    title: str
    state: str
    #: The severity the change is *judged* at -- an all-clear's peak, not its decayed Low.
    severity: str
    is_all_clear: bool
    changed_at: datetime.datetime
    related_event_id: uuid.UUID | None


@dataclass(frozen=True)
class ChangeRow:
    """One risk's day-over-day movement, as What Changed Since Yesterday reports it."""

    key: RiskKey
    previous_level: str
    current_level: str
    previous_score: float
    current_score: float
    #: Signed, so the direction is in the data and not only in the prose.
    delta: float
    #: The *level* changed, not merely the score. The spec's day-over-day rule turns on this:
    #: "any reversal must be acknowledged explicitly", and an unacknowledged one fails the
    #: grounding gate -- so the material flags it rather than leaving the composer to notice.
    is_reversal: bool

    @property
    def direction(self) -> str:
        if self.delta > 0:
            return "rose"
        if self.delta < 0:
            return "eased"
        return "unchanged"


# --------------------------------------------------------------------------------------
# Sections
# --------------------------------------------------------------------------------------


@dataclass(frozen=True)
class SectionMaterial:
    """One section's slot in the brief, with its structured rows and its citable claims.

    ``prose`` is empty for every section except the disclaimer, whose text is fixed. That is the
    seam: everything in here is deterministic, and everything the composer adds is prose.
    """

    kind: SectionKind
    order: int
    title: str
    #: Non-empty only where the text is *fixed* (the disclaimer). Never model output.
    prose: str = ""
    #: The claims the composer may cite in this section, and the only ids that may reach
    #: `report_sections.evidence_refs`. Claim ids -- never a historical episode id, which would
    #: resolve through `claim_evidence` to nothing.
    claim_ids: tuple[uuid.UUID, ...] = ()
    event: SelectedEvent | None = None
    evidence: EventEvidenceContext | None = None
    analogies: tuple[AnalogyContext, ...] = ()
    risk_rows: tuple[RiskRadarRow, ...] = ()
    forecast_rows: tuple[ForecastRow, ...] = ()
    alert_rows: tuple[AlertRow, ...] = ()
    change_rows: tuple[ChangeRow, ...] = ()
    quality_notes: tuple[DataQualityNote, ...] = ()
    #: Statements of fact about what this section could not draw on. Rendered as-is; they are
    #: not prose *about* the data, they are the absence of data, and the composer may not
    #: rewrite them away.
    notes: tuple[str, ...] = ()

    @property
    def is_placeholder(self) -> bool:
        """The composer must write this section's prose. True everywhere but the disclaimer."""
        return not self.prose


@dataclass(frozen=True)
class BriefMaterial:
    """The whole brief's deterministic skeleton, in reading order."""

    sections: tuple[SectionMaterial, ...] = field(default=())

    @property
    def kinds(self) -> tuple[SectionKind, ...]:
        return tuple(section.kind for section in self.sections)

    def of_kind(self, kind: SectionKind) -> tuple[SectionMaterial, ...]:
        return tuple(section for section in self.sections if section.kind is kind)

    @property
    def disclaimer(self) -> SectionMaterial:
        """Always the last section. See :func:`build_brief_material`."""
        return self.sections[-1]


# --------------------------------------------------------------------------------------
# Builders
# --------------------------------------------------------------------------------------


def _risk_rows(inputs: BriefInputs) -> tuple[RiskRadarRow, ...]:
    """The radar table: every risk with a standing score at this cutoff.

    Rows are built from `current`, not from `moves`, so a risk that did not move still appears.
    A radar that only showed movement would be a change log, and the standing level of a risk
    nobody re-scored is exactly the thing a risk radar exists to keep on the board.
    """
    previous = {entry.key: entry for entry in inputs.risk_radar.previous}
    rows = []
    for entry in inputs.risk_radar.current:
        prior = previous.get(entry.key)
        rows.append(
            RiskRadarRow(
                key=entry.key,
                score=entry.score,
                level=entry.level,
                as_of=entry.as_of,
                previous_score=prior.score if prior else None,
                previous_level=prior.level if prior else None,
                delta=round(entry.score - prior.score, 2) if prior else None,
                is_reversal=bool(prior and prior.level != entry.level),
            )
        )
    return tuple(rows)


def _change_rows(inputs: BriefInputs) -> tuple[ChangeRow, ...]:
    """Every measurable day-over-day move, reversals first.

    Ordered so the reversals lead: they are the ones the spec requires be acknowledged
    explicitly, and burying one under a larger but level-preserving move is how it goes
    unacknowledged.
    """
    rows = [
        ChangeRow(
            key=move.key,
            previous_level=move.previous.level,
            current_level=move.current.level,
            previous_score=move.previous.score,
            current_score=move.current.score,
            delta=move.delta,
            is_reversal=move.is_reversal,
        )
        for move in inputs.risk_radar.moves
    ]
    rows.sort(key=lambda row: (not row.is_reversal, -abs(row.delta), row.key))
    return tuple(rows)


def _alert_rows(changes: Sequence[AlertStateChange]) -> tuple[AlertRow, ...]:
    """The alert list, all-clears preserved.

    Resolutions are kept and marked, not filtered: an alert being stood down is information, and
    a brief that reported only escalations would ratchet a reader's sense of risk upward forever.
    """
    return tuple(
        AlertRow(
            alert_id=change.alert_id,
            title=change.title,
            state=change.state,
            severity=change.effective_severity,
            is_all_clear=change.is_all_clear,
            changed_at=change.changed_at,
            related_event_id=change.related_event_id,
        )
        for change in changes
    )


def _forecast_rows(
    forecasts: Sequence[EventForecast], events: Sequence[SelectedEvent]
) -> tuple[ForecastRow, ...]:
    """The forecast table, in event rank order then canonical scenario order. Table only.

    "forecasts table only" (report-generation spec, section budgets): there is no narrative
    field here and no place to put one, so a probability cannot be turned into a sentence
    without the composer doing it under the grounding gate's eye.
    """
    titles = {event.event_id: event for event in events}
    rows: list[ForecastRow] = []
    for forecast in sorted(
        forecasts, key=lambda item: titles[item.event_id].rank if item.event_id in titles else 0
    ):
        event = titles.get(forecast.event_id)
        if event is None:
            continue
        rows.extend(
            ForecastRow(
                event_id=forecast.event_id,
                event_title=event.title,
                scenario_set_id=forecast.scenario_set_id,
                scenario_name=scenario.scenario_name,
                probability=scenario.probability,
                risk_score=scenario.risk_score,
                severity=scenario.severity,
                horizon=scenario.horizon,
                confidence=scenario.confidence,
                evidence_refs=scenario.evidence_refs,
            )
            for scenario in forecast.scenarios
        )
    return tuple(rows)


def _what_changed_notes(inputs: BriefInputs, rows: Sequence[ChangeRow]) -> tuple[str, ...]:
    """State plainly when yesterday cannot be compared to today, and why.

    Two different absences, kept apart because they mean different things to a reader: no
    published brief yesterday (we said nothing to be consistent *with*), and no risk observed on
    both sides of the window (we said something, but nothing we can measure a move against).
    Either way the section still ships, saying what it cannot do.
    """
    notes: list[str] = []
    if inputs.prior_brief is None:
        notes.append(
            "No published brief exists for the previous day, so today's figures cannot be "
            "compared against what we previously reported."
        )
    if not rows:
        notes.append(
            "No risk carried an observation on both sides of the window, so no day-over-day "
            "movement could be measured."
        )
    return tuple(notes)


def build_brief_material(
    inputs: BriefInputs,
    context: BriefContext,
    *,
    prediction_backed_outputs_enabled: bool = False,
) -> BriefMaterial:
    """Lay out one brief's sections: which exist, in what order, and their exact rows.

    Sections are *omitted* rather than emptied when their data is missing (ADR 0009: "affected
    sections are omitted with an explicit data-quality note listing what's missing"), with two
    deliberate exceptions that always ship: What Changed Since Yesterday, and the disclaimer.

    On a quiet day -- zero events above the hotness floor -- there are no Top Event sections at
    all. The brief shrinks; it never pads. What survives is the risk radar, what changed, the
    quality notes explaining the quiet, and the disclaimer.
    """
    sections: list[SectionMaterial] = []
    notes: list[DataQualityNote] = [
        *inputs.data_quality_notes,
        *context.data_quality_notes,
    ]

    def add(kind: SectionKind, title: str, **payload: object) -> None:
        sections.append(SectionMaterial(kind=kind, order=len(sections) + 1, title=title, **payload))  # type: ignore[arg-type]

    # 1. Executive summary -- a placeholder. Its *inputs* were chosen by selection (alert state
    #    changes, top-2 events, largest risk move); its sentences are the composer's.
    add(
        SectionKind.EXECUTIVE_SUMMARY,
        "Executive Summary",
        claim_ids=_claim_ids_for(context, inputs.executive_summary.top_events),
    )

    # 2. Top Events -- zero to five. Never padded.
    for event in inputs.top_events[:MAX_TOP_EVENT_SECTIONS]:
        evidence = context.evidence_for(event.event_id)
        add(
            SectionKind.TOP_EVENT,
            event.title,
            event=event,
            evidence=evidence,
            claim_ids=evidence.claim_ids if evidence else (),
            notes=(
                ()
                if evidence and evidence.claims
                else ("No supportive article-linked claim is on record for this event.",)
            ),
        )

    # 3. Risk radar -- a structured table (plus the composer's <=60w commentary, later).
    risk_rows = _risk_rows(inputs)
    if risk_rows:
        add(SectionKind.RISK_RADAR, "Risk Radar", risk_rows=risk_rows)

    # 4. Historical parallels -- material where history has some, omitted where it does not.
    parallels = tuple(
        analogy
        for event in inputs.top_events
        for analogy in (
            context.analogies_for(event.event_id).analogies
            if context.analogies_for(event.event_id)
            else ()
        )
    )
    if parallels:
        add(SectionKind.HISTORICAL_PARALLELS, "Historical Parallels", analogies=parallels)

    # 5. Forecasts -- table only.
    if prediction_backed_outputs_enabled:
        forecast_rows = _forecast_rows(context.forecasts, inputs.top_events)
        if forecast_rows:
            add(SectionKind.FORECASTS, "Forecasts", forecast_rows=forecast_rows)

    # 6. Alerts -- list only, all-clears kept.
    if prediction_backed_outputs_enabled:
        alert_rows = _alert_rows(inputs.executive_summary.alert_state_changes)
        if alert_rows:
            add(SectionKind.ALERTS, "Alerts", alert_rows=alert_rows)

    # 7. What changed since yesterday -- always, even when the answer is "we cannot tell".
    change_rows = _change_rows(inputs)
    what_changed_notes = _what_changed_notes(inputs, change_rows)
    if what_changed_notes and not any(
        note.code is DataQuality.NO_PRIOR_COMPARISON for note in notes
    ):
        notes.append(DataQualityNote(DataQuality.NO_PRIOR_COMPARISON, " ".join(what_changed_notes)))
    add(
        SectionKind.WHAT_CHANGED,
        "What Changed Since Yesterday",
        change_rows=change_rows,
        notes=what_changed_notes,
    )

    # 8. Data quality -- only when there is something to declare.
    if notes:
        add(SectionKind.DATA_QUALITY, "Data Quality", quality_notes=tuple(notes))

    # 9. The disclaimer. Fixed text, and the last thing in every brief.
    add(SectionKind.DISCLAIMER, "Disclaimer", prose=FINAL_DISCLAIMER)

    return BriefMaterial(sections=tuple(sections))


def _claim_ids_for(context: BriefContext, events: Sequence[SelectedEvent]) -> tuple[uuid.UUID, ...]:
    """The claims the executive summary may cite: those of the events it is composed from."""
    seen: dict[uuid.UUID, None] = {}
    for event in events:
        evidence = context.evidence_for(event.event_id)
        if evidence is None:
            continue
        for claim_id in evidence.claim_ids:
            seen.setdefault(claim_id, None)
    return tuple(seen)
